#ifndef UBTMSG_H
#define UBTMSG_H

#include "globaldef.h"

#include <iostream>

using namespace std;

enum UBTMSG
{
    //UBTMSG_MSC_BASE = 0x10000,
    UBTMSG_NONE,
    UBTMSG_MSC_TTS_RECVDATA,
    UBTMSG_MSC_TTS_END,
    UBTMSG_MSC_WAKEUP,
    UBTMSG_MSC_EXPECT_SPEECH_START,
    UBTMSG_MSC_RECOGCMD_START,
    UBTMSG_MSC_RECOGCMD_RESTART,
    UBTMSG_MSC_RECOGCMD_PARSING,
    UBTMSG_MSC_RECOGCMD_END,
    UBTMSG_MSC_RECOGCMD_OFFLINERESULT,
    UBTMSG_MSC_RECOGCMD_ONLINERESULT,
    UBTMSG_MSC_RECOGCMD_RESULT_DETAILS,
    UBTMSG_MSC_RECOGCMD_NORESULT,
    UBTMSG_MSC_RECOGCMD_ERROR,
    UBTMSG_MSC_SEMANTIC_RESULT,
    UBTMSG_MSC_SERVICE_CREATE,
    UBTMSG_MSC_VAD_TIMEOUT,
    UBTMSG_DINGDANG_MSC_TTS_FACE_EVENT,
    UBTMSG_DINGDANG_MSC_TTS_FACE_END_EVENT,
    UBTMSG_DINGDANG_MSC_WINDOW_EVENT,
    UBTMSG_DINGDANG_MSC_PLAYMODE_EVENT,
    UBTMSG_DINGDANG_MSC_SHUTDOWN,
    UBTMSG_DINGDANG_MSC_SHOW_QRCODE,
    UBTMSG_DINGDANG_MSC_MUTE,

    //UBTMSG_UBTAUDIO_BASE = 0x20000,
    UBTMSG_UBTAUDIO_ERROR,
    UBTMSG_UBTAUDIO_PLAYER_NOTHING,
    UBTMSG_UBTAUDIO_URI_PLAYSTART,
    UBTMSG_UBTAUDIO_URI_PLAYSTOP,
    UBTMSG_UBTAUDIO_URI_PLAYPAUSE,
    UBTMSG_UBTAUDIO_URI_PLAYFINISH,
    UBTMSG_UBTAUDIO_URI_PLAYRESUME,
    UBTMSG_UBTAUDIO_URI_PLAYPROGRESS,
    UBTMSG_UBTAUDIO_URI_DROP,
    UBTMSG_UBTAUDIO_URI_FAILED,
    UBTMSG_UBTAUDIO_PROMPT_PLAYSTART,
    UBTMSG_UBTAUDIO_PROMPT_PLAYSTOP,
    UBTMSG_UBTAUDIO_PROMPT_PLAYPAUSE,
    UBTMSG_UBTAUDIO_PROMPT_PLAYFINISH,
    UBTMSG_UBTAUDIO_PROMPT_PLAYRESUME,
    UBTMSG_UBTAUDIO_PROMPT_PLAYPROGRESS,
    UBTMSG_UBTAUDIO_PROMPT_DROP,
    UBTMSG_UBTAUDIO_TTS_PLAYSTART,
    UBTMSG_UBTAUDIO_TTS_PLAYSTOP,
    UBTMSG_UBTAUDIO_TTS_PLAYPAUSE,
    UBTMSG_UBTAUDIO_TTS_PLAYFINISH,
    UBTMSG_UBTAUDIO_TTS_PLAYRESUME,
    UBTMSG_UBTAUDIO_TTS_PLAYPROGRESS,
    UBTMSG_UBTAUDIO_TTS_DROP,
    UBTMSG_UBTAUDIO_BT_PLAYSTART,
    UBTMSG_UBTAUDIO_BT_PLAYSTOP,
    UBTMSG_UBTAUDIO_BT_PLAYPAUSE,
    UBTMSG_UBTAUDIO_BT_PLAYFINISH,
    UBTMSG_UBTAUDIO_BT_PLAYRESUME,
    UBTMSG_UBTAUDIO_BT_PLAYPROGRESS,
    UBTMSG_UBTAUDIO_BT_DROP,
    UBTMSG_UBTAUDIO_RECORD_RECVDATA,
    UBTMSG_UBTAUDIO_EXPERSSION_DIR,
    UBTMSG_UBTAUDIO_RECOGNISE_TIMEOUT,
    UBTMSG_UBTAUDIO_CLOSED_BT_DIR,
    UBTMSG_UBTAUDIO_OPENNED_BT_DIR,
    UBTMSG_UBTAUDIO_SHOW_BATTERY_DIR,
    UBTMSG_UBTAUDIO_NET_CONFIG_DIR,
    UBTMSG_UBTAUDIO_WAKE_UP_DIR,
    UBTMSG_UBTAUDIO_ALERT,
    UBTMSG_UBTAUDIO_COIN,
    UBTMSG_UBTAUDIO_START_PROGRESS,

    //UBTMSG_ROBOT_BASE = 0x30000,
    UBTMSG_ROBOT_FALLED_DOWN,
    UBTMSG_ROBOT_FALLED_DOWN_SOFT,
    UBTMSG_ROBOT_TILT_EVENT,

    //UBTMSG_ALERT_ALARM_BASE = 0x40000,
    UBTMSG_ALERT_ALARM_TIMEOUT_START,
    UBTMSG_ALERT_ALARM_TIMEOUT_END,
    UBTMSG_ALERT_ALARM_REAL_START,

    //UBTMSG_BATTERY_BASE = 0x50000,
    UBTMSG_BATTERY_LOWPOWER,
    UBTMSG_BATTERY_NORMALPOWER,
    UBTMSG_BATTERY_CHARGINE,
    UBTMSG_BATTERY_FULLCHARGED,
    UBTMSG_BATTERY_DISCHARGINE,
    UBTMSG_BATTERY_VALUE_CHANGE,
    UBTMSG_BATTERY_STAT_CHANGE,
    UBTMSG_BATTERY_STANDBY_MODE,
    UBTMSG_BATTERY_NORMAL_MODE,

    //UBTMSG_BLUETOOTH_BASE = 0x60000,
    UBTMSG_BLUETOOTH_LINEOFF,
    UBTMSG_BLUETOOTH_LINEON,
    UBTMSG_BLUETOOTH_RECEIVEDATA,
    UBTMSG_BLUETOOTH_DEVICE_OPEN,
    UBTMSG_BLUETOOTH_DEVICE_CLOSE,

    //UBTMSG_INITIAL_BOOT_BASE = 0x70000,
    UBTMSG_INITIAL_BOOT_SHOWQR_ENTER,
    UBTMSG_INITIAL_BOOT_SHOWQR_LEAVE,
    UBTMSG_INITIAL_BOOT_ENTER_NETWORKCONFIG,
    UBTMSG_INITIAL_BOOT_LEAVE_NETWORKCONFIG,
    UBTMSG_INITIAL_BOOT_INTRADUCTION_ENTER,
    UBTMSG_INITIAL_BOOT_RE_ENTER,
    UBTMSG_INITIAL_BOOT_ENTER,
    UBTMSG_INITIAL_BOOT_LEAVE,

    //UBTMSG_ALERT_REMINDER_BASE = 0x80000,
    UBTMSG_ALERT_REMINDER_TIMEOUT_START,
    UBTMSG_ALERT_REMINDER_TIMEOUT_END,
    UBTMSG_ALERT_REMINDER_REAL_START,
    UBTMSG_ALERT_REMINDER_TIMEOUT_INTERRUPT,

    //UBTMSG_SYSTEMKEY_BASE = 0x90000,
    UBTMSG_SYSTEMKEY_POWERKEY_LONGPRESS,
    UBTMSG_SYSTEMKEY_POWER_ONECLICK_EVENT,
    UBTMSG_SYSTEMKEY_INSERTCOIN,
    UBTMSG_SYSTEMKEY_VOLUMEUP_PRESS,
    UBTMSG_SYSTEMKEY_VOLUMEUP_RELEASE,
    UBTMSG_SYSTEMKEY_VOLUMEDOWN_PRESS,
    UBTMSG_SYSTEMKEY_VOLUMEDOWN_RELEASE,
    UBTMSG_SYSTEMKEY_VOLUME_BOTH_PRESS,
    UBTMSG_SYSTEMKEY_NET_CONFIG,
    UBTMSG_SYSTEMKEY_EXIT_NET_CONFIG,
    UBTMSG_FACTORY_RESET_EVENT,
    UBTMSG_SYSTEMKEY_TOUCHED,
    UBTMSG_SYSTEMKEY_SUBTYPE_TOUCH_A,
    UBTMSG_SYSTEMKEY_SUBTYPE_SCRATCH_A,
    UBTMSG_SYSTEMKEY_SUBTYPE_TOUCH_B1,
    UBTMSG_SYSTEMKEY_SUBTYPE_SCRATCH_B1,
    UBTMSG_SYSTEMKEY_SUBTYPE_TOUCH_B2,
    UBTMSG_SYSTEMKEY_SUBTYPE_SCRATCH_B2,
    UBTMSG_SYSTEMKEY_SUBTYPE_MIXED_TOUCH_B1B2,
    UBTMSG_SYSTEMKEY_SUBTYPE_TOUCH__B1B2_AT_SAME_TIME,
    UBTMSG_SYSTEMKEY_SUBTYPE_TOUCH_STAGE_2,
    UBTMSG_SYSTEMKEY_SUBTYPE_TOUCH_STAGE_3,
    UBTMSG_SYSTEMKEY_TOUCHED_HEAD,

    //UBTMSG_SYSTEM_SETING_BASE = 0xA0000,
    UBTMSG_SYSTEM_CLOCKALARM,
    UBTMSG_SYSTEMKEY_EVENT_PRESS,
    UBTMSG_SYSTEMKEY_EVENT_DOUBLE_PRESS,
    UBTMSG_SYSTEMKEY_EVENT_RELEASE,
    UBTMSG_SYSVOLUME_SETTING,
    UBTMSG_SYSTEM_STATUS_CHANGE,
    UBTMSG_GET_SPEAKER_STATUS,

    //UBTMSG_UPDATE_BASE = 0xB0000,
    UBTMSG_UBTREADAUTOUPDATESTATE,
    UBTMSG_UBTSETAUTOUPDATESTATE,
    UBTMSG_UBTREADAUTOUPDATEPROGRESS,
    UBTMSG_UBTINSTALLING_UPDATE,
    UBTMSG_UBTINSTALLED_UPDATESUEECESS,

    //UBTMSG_NETWORKSTATE_BASE = 0xC0000,
    UBTMSG_NETWORKSTATE_CHANGED,

    UBTMSG_MAX,
};


struct TaskMsg
{
    int msg;
    int ctx;
    zxLib::WPARAM wparam;
    zxLib::LPARAM lparam;
    string str_msg;
};

struct MscSrvMsg
{
    string tts;
    string service;
    string operation;
    string semantic_json;
    bool   session;
};

#endif // UBTMSG_H
